name: Lint markdown
on: [push, pull_request]

jobs:
  lint:
    name: Check Markdown styling (lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: ./docs
          config_file: .markdownlint.json
          dot: true
          ignore_path: .markdownlintignore