name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys:
            mkdocs-material
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
      - name: Discord Commits
        uses: Tedeapolis/discord-commits@v1.2.5
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: "${{ env.WEBHOOK != '' }}"
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Successful commit to **{{ github.context.payload.repository.name}}**.\nDiff: {{ github.context.payload.compare }}"
          embed: '{"title":"{{ commit.title }}","description":"{{ commit.description }}","url":"{{ commit.url }}","author":{"name":"{{ commit.author.name }}","icon_url":"https://github.com/{{ commit.author.username ?? commit.author.name }}.png"}}'
